# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_appt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='date',
            field=models.DateField(default='2016-08-23'),
            preserve_default=False,
        ),
    ]
