# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_appt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='time',
            field=models.TimeField(),
        ),
    ]
